language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
after_script:
  - npm run coveralls
notifications:
  email:
    - denis@w3.org
    - antonio@w3.org
  irc:
    channels:
      - "irc.w3.org#pubrules"
    skip_join: true
